export const PARTS={
shell:{name:'Rear cabinet',summary:'Lớp vỏ ngoài bảo vệ CRT và chassis, đồng thời tạo khoảng cách an toàn quanh phần cao áp.',fn:'Che chắn cơ khí, định hướng luồng khí và giữ khoảng cách với các phần điện áp cao.',mat:'Nhựa kỹ thuật đúc; exterior 3D dùng asset tham khảo CC BY 4.0.',evidence:'Exterior asset: visual reference · shell function: verified engineering topology.'},
crt:{name:'Trinitron picture tube',summary:'Ống chân không lớn chiếm phần lớn thể tích và khối lượng của TV.',fn:'Gia tốc và dẫn chùm electron đến lớp phosphor ở mặt trước để tạo hình ảnh.',mat:'Glass envelope, phosphor screen, shadow/aperture structure, conductive coating.',evidence:'Verified device class + BA‑4D picture-tube removal procedure; geometry reconstructed.'},
yoke:{name:'Deflection yoke',summary:'Cụm cuộn dây ôm quanh cổ CRT để bẻ hướng chùm electron theo ngang và dọc.',fn:'Quét electron theo raster để chùm tia tới đúng vị trí trên màn hình.',mat:'Copper windings, ferrite core, insulating frame.',evidence:'Verified CRT component; BA‑4D manual includes DY corrections and setup procedures.'},
gun:{name:'Electron gun',summary:'Cụm điện cực nằm trong cổ ống CRT, tạo và hội tụ chùm electron.',fn:'Phát, điều biến, gia tốc và focus các electron trước khi chúng đi qua yoke.',mat:'Metal cathodes, grids, focus/anode electrodes inside vacuum.',evidence:'Verified CRT topology; internal geometry is illustrative reconstruction.'},
aboard:{name:'A board / main chassis',summary:'Board chính của BA‑4D chứa phần lớn tuner/IF, video, deflection, audio và nguồn liên quan.',fn:'Nhận tín hiệu, xử lý video/audio và điều khiển các khối quét/nguồn của TV.',mat:'Large FR‑4 PCB, ICs, capacitors, resistors, heatsinks, connectors.',evidence:'A board location and functions documented in BA‑4D service manual; placement reconstructed.'},
power:{name:'Power section',summary:'Khu vực nguồn trên chassis tạo các đường điện áp cần thiết cho logic, audio và phần quét.',fn:'Rectification, regulation, switching and high-current distribution.',mat:'Transformer, electrolytic capacitors, coils, fuse, power semiconductors and heatsinks.',evidence:'Circuit topology verified from service documentation; 3D arrangement reconstructed.'},
flyback:{name:'Flyback / high voltage',summary:'Biến áp cao áp tạo điện áp anode CRT và các điện áp phụ liên quan đến quét/focus.',fn:'Tạo điện áp rất cao cho anode CRT đồng bộ với horizontal deflection.',mat:'Ferrite transformer core, wound coils, molded insulation, high-voltage lead.',evidence:'Flyback generator documented in BA‑4D diagrams; geometry reconstructed.'},
cboard:{name:'C board / neck board',summary:'Board nhỏ gắn ở cổ CRT, nối trực tiếp với chân electron gun.',fn:'Đưa các tín hiệu drive RGB và điện áp cần thiết tới electron gun.',mat:'Small FR‑4 PCB, CRT socket, transistors/resistors and connectors.',evidence:'C board listed in BA‑4D board-location documentation.'},
speakers:{name:'Speaker pair',summary:'Hai driver điện động tạo âm thanh ở hai bên cabinet.',fn:'Biến tín hiệu audio khuếch đại thành dao động màng loa.',mat:'Magnet, voice coil, cone/surround, stamped frame.',evidence:'KV‑27S42 service specification lists 5 W × 2 speaker output; geometry reconstructed.'},
tuner:{name:'RF tuner cage',summary:'Module kim loại nhận RF antenna/cable trước khi tín hiệu đi sang khối xử lý IF/video.',fn:'Tuning and RF/IF front-end conversion.',mat:'Shielded metal can, RF connector, tuned circuitry.',evidence:'Tuner/IF functions documented on A board; geometry reconstructed.'}
};
