import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';

const clamp=THREE.MathUtils.clamp;
const rounded=(w,h,d,r=.05,s=4)=>new RoundedBoxGeometry(w,h,d,s,r);
function seeded(seed=1337){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296)}
function curvedPanel(w,h,sx=32,sy=24,curve=.16){const g=new THREE.PlaneGeometry(w,h,sx,sy);const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i)/(w*.5),y=p.getY(i)/(h*.5);p.setZ(i,curve*(1-(x*x*.55+y*y*.45)))}p.needsUpdate=true;g.computeVertexNormals();return g}
function screenTexture(){const c=document.createElement('canvas');c.width=1024;c.height=768;const x=c.getContext('2d');x.fillStyle='#071018';x.fillRect(0,0,c.width,c.height);const bars=['#d9d9d9','#e6df45','#44d8d3','#49d967','#d34fd0','#e14a49','#4e5bdb'];bars.forEach((col,i)=>{x.fillStyle=col;x.globalAlpha=.82;x.fillRect(i*c.width/bars.length,90,c.width/bars.length,420)});x.globalAlpha=1;x.fillStyle='#070707';x.fillRect(0,510,c.width,258);x.fillStyle='#a7b9c8';x.font='700 34px ui-monospace,monospace';x.fillText('KV-27S42  //  BA-4D',55,610);x.fillStyle='#597082';x.font='22px ui-monospace,monospace';x.fillText('TRINITRON SIGNAL MONITOR',55,650);for(let y=0;y<c.height;y+=4){x.fillStyle='rgba(0,0,0,.14)';x.fillRect(0,y,c.width,1)}for(let i=0;i<700;i++){const a=Math.random()*.08;x.fillStyle=`rgba(255,255,255,${a})`;x.fillRect(Math.random()*c.width,Math.random()*c.height,1,1)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t}

export class CRTExperience{
constructor(host){
 this.host=host;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x05070a);this.scene.fog=new THREE.FogExp2(0x05070a,.035);
 this.camera=new THREE.PerspectiveCamera(35,1,.05,100);this.camera.position.set(7.8,2.8,11.4);
 this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.0;host.appendChild(this.renderer.domElement);
 const pm=new THREE.PMREMGenerator(this.renderer);this.scene.environment=pm.fromScene(new RoomEnvironment(),.035).texture;pm.dispose();
 this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.055;this.controls.enablePan=false;this.controls.minDistance=6.5;this.controls.maxDistance=16;this.controls.target.set(.1,-.1,-.25);
 this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.explode=0;this.targetExplode=0;this.xray=false;this.beam=false;this.autoRotate=true;this.selected='shell';this.parts=new Map();this.exterior=null;this.exteriorMeshes=[];this.interior=new THREE.Group();this.scene.add(this.interior);
 this.setupLights();this.setupStage();this.buildInterior();this.buildBeam();this.installEvents();this.loadExterior();this.resize();addEventListener('resize',()=>this.resize());this.animate=this.animate.bind(this);requestAnimationFrame(this.animate);
}
setupLights(){const key=new THREE.SpotLight(0xffffff,95,28,Math.PI*.19,.46,1.4);key.position.set(6,8,8);key.target.position.set(0,0,-.5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);this.scene.add(key,key.target);const rim=new THREE.SpotLight(0x8fc9ee,70,24,Math.PI*.24,.55,1.5);rim.position.set(-7,4,-5);rim.target.position.set(0,.3,-.8);this.scene.add(rim,rim.target);const fill=new THREE.DirectionalLight(0xbfd3e2,.8);fill.position.set(-3,1,8);this.scene.add(fill)}
setupStage(){const floor=new THREE.Mesh(new THREE.CircleGeometry(8.5,96),new THREE.MeshPhysicalMaterial({color:0x080b0f,roughness:.62,metalness:.1,clearcoat:.05}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.7;floor.receiveShadow=true;this.scene.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(6.1,.012,5,160),new THREE.MeshBasicMaterial({color:0x25313a,transparent:true,opacity:.35}));ring.rotation.x=Math.PI/2;ring.position.y=-2.685;this.scene.add(ring)}
matMetal(c=0x747d85,r=.28){return new THREE.MeshPhysicalMaterial({color:c,metalness:.88,roughness:r,clearcoat:.08})}
matDark(c=0x11161b,r=.42){return new THREE.MeshPhysicalMaterial({color:c,metalness:.08,roughness:r,clearcoat:.12,clearcoatRoughness:.4})}
mesh(g,m,cast=true){const x=new THREE.Mesh(g,m);x.castShadow=cast;x.receiveShadow=true;return x}
register(id,g,base,dir){g.userData.part=id;g.userData.base=base.clone();g.userData.dir=dir.clone();g.position.copy(base);g.traverse(o=>{if(o.isMesh){o.userData.part=id;o.userData.baseColor=o.material?.color?.getHex?.()}});this.parts.set(id,g);this.interior.add(g)}

buildInterior(){
 const chassis=new THREE.Group(),steel=this.matMetal(0x636c73,.36);const rails=[[0,-1.95,-.35,5.7,.12,.22],[0,1.65,-.15,5.7,.1,.18],[-2.72,-.2,-.35,.16,3.35,.25],[2.72,-.2,-.35,.16,3.35,.25]];rails.forEach(v=>{const m=this.mesh(rounded(v[3],v[4],v[5],.04),steel);m.position.set(v[0],v[1],v[2]);chassis.add(m)});for(let i=0;i<4;i++){const brace=this.mesh(rounded(.1,3.2,.12,.025),steel);brace.position.set(-1.75+i*1.15,-.18,-.5);brace.rotation.z=(i%2?.06:-.06);chassis.add(brace)}this.register('chassis',chassis,new THREE.Vector3(0,0,-.2),new THREE.Vector3(-.4,.15,-.95));

 const tube=new THREE.Group();const pts=[new THREE.Vector2(.25,-2.2),new THREE.Vector2(.26,-1.85),new THREE.Vector2(.34,-1.55),new THREE.Vector2(.55,-1.25),new THREE.Vector2(1.15,-.9),new THREE.Vector2(1.95,-.48),new THREE.Vector2(2.52,-.1),new THREE.Vector2(2.6,.18),new THREE.Vector2(2.56,.32)];const bellGeo=new THREE.LatheGeometry(pts,96);bellGeo.rotateX(Math.PI/2);const glass=new THREE.MeshPhysicalMaterial({color:0x40535e,metalness:.02,roughness:.16,transmission:.28,transparent:true,opacity:.58,thickness:.55,ior:1.52,clearcoat:1,clearcoatRoughness:.05,side:THREE.DoubleSide});const bell=this.mesh(bellGeo,glass,false);bell.scale.y=.73;tube.add(bell);const face=this.mesh(curvedPanel(4.92,3.62,48,34,.17),new THREE.MeshPhysicalMaterial({map:screenTexture(),emissive:0xffffff,emissiveMap:screenTexture(),emissiveIntensity:.78,roughness:.12,clearcoat:1,clearcoatRoughness:.045,metalness:.02}),false);face.position.set(0,0,.37);tube.add(face);const phosphor=this.mesh(curvedPanel(4.78,3.48,40,30,.145),new THREE.MeshBasicMaterial({color:0x78a8a3,transparent:true,opacity:.11,side:THREE.DoubleSide}),false);phosphor.position.set(0,0,.28);tube.add(phosphor);this.register('crt',tube,new THREE.Vector3(0,.1,-.05),new THREE.Vector3(0,.12,1.25));

 const gun=new THREE.Group(),brass=new THREE.MeshPhysicalMaterial({color:0xb58b52,metalness:.82,roughness:.24}),gunMetal=this.matMetal(0xbfc4c7,.18);for(let i=0;i<6;i++){const r=.10+i*.018;const cyl=this.mesh(new THREE.CylinderGeometry(r,r,.22,32),i%2?brass:gunMetal);cyl.rotation.x=Math.PI/2;cyl.position.z=-2.26+i*.22;gun.add(cyl);const ring=this.mesh(new THREE.TorusGeometry(r+.04,.018,10,34),brass);ring.position.z=cyl.position.z+.1;gun.add(ring)}for(let a=-.11;a<=.11;a+=.11){const rod=this.mesh(new THREE.CylinderGeometry(.012,.012,1.1,12),gunMetal);rod.rotation.x=Math.PI/2;rod.position.set(a,0,-1.75);gun.add(rod)}this.register('gun',gun,new THREE.Vector3(0,.1,0),new THREE.Vector3(0,.2,-1.45));

 const yoke=new THREE.Group(),core=new THREE.MeshPhysicalMaterial({color:0x24282b,metalness:.12,roughness:.48}),copper=new THREE.MeshPhysicalMaterial({color:0xb7662f,metalness:.78,roughness:.28});const tor=this.mesh(new THREE.TorusGeometry(.62,.15,18,60),core);tor.position.z=-1.28;yoke.add(tor);for(let i=0;i<8;i++){const coil=this.mesh(new THREE.TorusGeometry(.58+i*.014,.018,10,64),copper);coil.position.z=-1.28+(i-3.5)*.025;coil.scale.y=.76;yoke.add(coil)}for(let i=0;i<4;i++){const c=this.mesh(new THREE.TorusGeometry(.48,.028,10,48,Math.PI*1.25),copper);c.position.z=-1.27;c.rotation.z=i*Math.PI/2;c.scale.set(1,.7,1);yoke.add(c)}this.register('yoke',yoke,new THREE.Vector3(0,.1,0),new THREE.Vector3(.95,.65,-.65));

 const board=new THREE.Group(),pcb=new THREE.MeshPhysicalMaterial({color:0x224f3a,roughness:.43,metalness:.07,clearcoat:.08});const base=this.mesh(rounded(4.8,.1,3.35,.045),pcb);board.add(base);const rnd=seeded(42);const black=new THREE.MeshPhysicalMaterial({color:0x0e1114,roughness:.3,metalness:.22});for(let i=0;i<42;i++){const w=.12+rnd()*.34,d=.1+rnd()*.28,h=.06+rnd()*.12;const chip=this.mesh(rounded(w,h,d,.018),black);chip.position.set((rnd()-.5)*4.2,.11+h*.45,(rnd()-.5)*2.85);board.add(chip)}const capColors=[0x26384a,0x463021,0x1d2e24];for(let i=0;i<16;i++){const r=.07+rnd()*.07,h=.2+rnd()*.34;const cap=this.mesh(new THREE.CylinderGeometry(r,r,h,22),new THREE.MeshPhysicalMaterial({color:capColors[i%3],metalness:.22,roughness:.3}));cap.position.set((rnd()-.5)*3.9,.1+h*.5,(rnd()-.5)*2.6);board.add(cap)}for(let i=0;i<6;i++){const sink=new THREE.Group();for(let f=0;f<6;f++){const fin=this.mesh(rounded(.04,.44,.46,.01),this.matMetal(0x616b72,.35));fin.position.x=(f-2.5)*.075;sink.add(fin)}sink.position.set((rnd()-.5)*3.4,.32,(rnd()-.5)*2.4);board.add(sink)}this.register('aboard',board,new THREE.Vector3(0,-1.78,-.62),new THREE.Vector3(0,-1.25,.2));

 const power=new THREE.Group();const tx=this.mesh(rounded(.62,.75,.66,.06),new THREE.MeshPhysicalMaterial({color:0x26221b,roughness:.5,metalness:.1}));tx.position.set(-1.55,.42,-.7);power.add(tx);for(let i=0;i<3;i++){const cap=this.mesh(new THREE.CylinderGeometry(.13,.13,.52,28),new THREE.MeshPhysicalMaterial({color:i===0?0x273648:0x3a2d25,metalness:.18,roughness:.32}));cap.position.set(-.95+i*.34,.36,-.18+i*.12);power.add(cap)}const coil=this.mesh(new THREE.TorusGeometry(.24,.06,12,40),copper);coil.rotation.x=Math.PI/2;coil.position.set(-1.1,.3,.66);power.add(coil);const fuse=this.mesh(new THREE.CylinderGeometry(.045,.045,.42,18),new THREE.MeshPhysicalMaterial({color:0xdbe6df,transmission:.55,transparent:true,opacity:.75,roughness:.08}));fuse.rotation.z=Math.PI/2;fuse.position.set(-1.72,.2,.55);power.add(fuse);this.register('power',power,new THREE.Vector3(0,-1.78,-.62),new THREE.Vector3(-1.05,-.7,.4));

 const fly=new THREE.Group();const flybody=this.mesh(rounded(.62,.9,.68,.07),new THREE.MeshPhysicalMaterial({color:0x111417,roughness:.38,metalness:.08}));fly.add(flybody);for(let i=0;i<7;i++){const ring=this.mesh(new THREE.TorusGeometry(.19+i*.014,.025,12,40),new THREE.MeshPhysicalMaterial({color:0x2d3338,metalness:.4,roughness:.35}));ring.rotation.x=Math.PI/2;ring.position.y=.36;fly.add(ring)}const tower=this.mesh(new THREE.CylinderGeometry(.16,.22,.72,28),new THREE.MeshPhysicalMaterial({color:0x16191c,roughness:.32}));tower.position.y=.72;fly.add(tower);this.register('flyback',fly,new THREE.Vector3(1.62,-1.2,-.75),new THREE.Vector3(1.18,-.8,-.45));
 const cableCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(1.62,-.7,-.75),new THREE.Vector3(2.05,-.1,-.42),new THREE.Vector3(1.95,.5,-.1),new THREE.Vector3(1.55,.65,.08)]);const cable=this.mesh(new THREE.TubeGeometry(cableCurve,48,.035,10,false),new THREE.MeshPhysicalMaterial({color:0x9d2422,roughness:.48}),false);fly.add(cable);const capAnode=this.mesh(new THREE.CylinderGeometry(.13,.19,.08,28),new THREE.MeshPhysicalMaterial({color:0x222426,roughness:.6}));capAnode.rotation.x=Math.PI/2;capAnode.position.set(-.07,1.86,.83);fly.add(capAnode);

 const cboard=new THREE.Group(),cb=this.mesh(rounded(1.05,1.18,.09,.035),pcb);cboard.add(cb);const socket=this.mesh(new THREE.CylinderGeometry(.24,.24,.16,32),new THREE.MeshPhysicalMaterial({color:0xd6d0ba,roughness:.35}));socket.rotation.x=Math.PI/2;socket.position.z=.08;cboard.add(socket);for(let i=0;i<9;i++){const pin=this.mesh(new THREE.CylinderGeometry(.012,.012,.18,10),gunMetal);pin.rotation.x=Math.PI/2;const a=i/9*Math.PI*2;pin.position.set(Math.cos(a)*.18,Math.sin(a)*.18,.17);cboard.add(pin)}this.register('cboard',cboard,new THREE.Vector3(0,.12,-2.42),new THREE.Vector3(-.65,.45,-1.0));

 const tuner=new THREE.Group(),can=this.mesh(rounded(.9,.42,1.18,.035),this.matMetal(0xb0b4b8,.24));tuner.add(can);const jack=this.mesh(new THREE.CylinderGeometry(.09,.09,.35,28),this.matMetal(0xd0d3d5,.18));jack.rotation.x=Math.PI/2;jack.position.set(.28,.02,.73);tuner.add(jack);this.register('tuner',tuner,new THREE.Vector3(1.35,-1.48,.52),new THREE.Vector3(.9,-.4,.7));

 const speakers=new THREE.Group();for(const sx of[-2.65,2.65]){const sp=new THREE.Group(),basket=this.mesh(new THREE.CylinderGeometry(.52,.43,.26,42),this.matMetal(0x4a5156,.42));basket.rotation.x=Math.PI/2;sp.add(basket);const cone=this.mesh(new THREE.CylinderGeometry(.12,.43,.16,50,1,true),new THREE.MeshPhysicalMaterial({color:0x25292c,roughness:.6,side:THREE.DoubleSide}));cone.rotation.x=Math.PI/2;cone.position.z=.18;sp.add(cone);const surround=this.mesh(new THREE.TorusGeometry(.42,.045,14,50),new THREE.MeshPhysicalMaterial({color:0x0b0d0e,roughness:.72}));surround.position.z=.28;sp.add(surround);const magnet=this.mesh(new THREE.CylinderGeometry(.25,.25,.26,32),new THREE.MeshPhysicalMaterial({color:0x171a1c,metalness:.42,roughness:.38}));magnet.rotation.x=Math.PI/2;magnet.position.z=-.26;sp.add(magnet);sp.position.set(sx,-.55,.12);speakers.add(sp)}this.register('speakers',speakers,new THREE.Vector3(0,0,0),new THREE.Vector3(0,-.4,.5));
}

buildBeam(){this.beamGroup=new THREE.Group();this.scene.add(this.beamGroup);const beamMat=new THREE.MeshBasicMaterial({color:0x8be8ff,transparent:true,opacity:.8});this.beamCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,.1,-2.1),new THREE.Vector3(0,.1,-1.25),new THREE.Vector3(.02,.08,-.45),new THREE.Vector3(.05,.05,.22)]);this.beamLine=this.mesh(new THREE.TubeGeometry(this.beamCurve,50,.014,8,false),beamMat,false);this.beamGroup.add(this.beamLine);this.beamDot=this.mesh(new THREE.SphereGeometry(.055,18,18),new THREE.MeshBasicMaterial({color:0xc8f7ff}),false);this.beamGroup.add(this.beamDot);this.beamGroup.visible=false}
async loadExterior(){try{const gltf=await new GLTFLoader().loadAsync('https://raw.githubusercontent.com/TheMarco/liminal/main/models/cc_by/retro_television/retro_television.glb');const root=gltf.scene;root.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(root),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);const scale=6.05/(Math.max(size.x,size.y,size.z)||1);root.scale.setScalar(scale);root.position.copy(center).multiplyScalar(-scale);root.rotation.y=Math.PI;root.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;o.userData.part='shell';o.userData.basePosition=o.position.clone();if(Array.isArray(o.material))o.material=o.material.map(m=>m.clone());else if(o.material)o.material=o.material.clone();for(const m of(Array.isArray(o.material)?o.material:[o.material]))if(m)m.userData.baseOpacity=m.opacity??1;this.exteriorMeshes.push(o)});this.exterior=root;this.scene.add(root);this.updateVisibility();this.onReady?.()}catch(e){console.error(e);this.onReady?.();}}
installEvents(){this.renderer.domElement.addEventListener('pointermove',e=>this.pick(e,false));this.renderer.domElement.addEventListener('pointerdown',e=>this.pick(e,true));this.controls.addEventListener('start',()=>{this.autoRotate=false})}
pick(e,click){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const arr=[];this.parts.forEach(g=>g.traverse(o=>{if(o.isMesh&&o.visible)arr.push(o)}));if(this.exterior?.visible)this.exterior.traverse(o=>{if(o.isMesh)arr.push(o)});const hit=this.raycaster.intersectObjects(arr,false)[0];this.renderer.domElement.style.cursor=hit?'pointer':'grab';if(click&&hit?.object?.userData?.part){const id=hit.object.userData.part;this.selectPart(id);this.onSelect?.(id)}}
selectPart(id){this.selected=id;this.parts.forEach((g,pid)=>g.traverse(o=>{if(!o.isMesh||!o.material)return;for(const m of(Array.isArray(o.material)?o.material:[o.material])){if(!m)return;if(m.color&&o.userData.baseColor!==undefined)m.color.setHex(o.userData.baseColor);if('emissive' in m)m.emissiveIntensity=0;if(pid===id){if('emissive' in m){m.emissive?.setHex?.(0x163042);m.emissiveIntensity=.42}else if(m.color)m.color.offsetHSL(0,0,.08)}}}));}
focusPart(id){if(id==='shell'&&this.exterior){const c=new THREE.Vector3();new THREE.Box3().setFromObject(this.exterior).getCenter(c);this.controls.target.lerp(c,.85);return}const g=this.parts.get(id);if(!g)return;const c=new THREE.Vector3();new THREE.Box3().setFromObject(g).getCenter(c);this.controls.target.lerp(c,.9)}
setExplode(v){this.targetExplode=clamp(v,0,1)}
toggleXray(){this.xray=!this.xray;this.updateVisibility();return this.xray}
toggleBeam(){this.beam=!this.beam;this.beamGroup.visible=this.beam;return this.beam}
reset(){this.camera.position.set(7.8,2.8,11.4);this.controls.target.set(.1,-.1,-.25);this.controls.update()}
updateVisibility(){const e=this.explode;this.parts.forEach((g,id)=>{g.visible=e>.018||this.xray;const alpha=this.xray?.9:clamp((e-.01)*3.6,0,1);g.traverse(o=>{if(!o.isMesh||!o.material)return;for(const m of(Array.isArray(o.material)?o.material:[o.material])){if(!m)return;const base=m.userData.baseOpacity??m.opacity??1;if(this.xray){m.transparent=base<1;m.opacity=base}else{m.transparent=base<1||alpha<.999;m.opacity=base*alpha;m.depthWrite=alpha>.25}}})});if(this.exterior){const opacity=this.xray?.14:clamp(1-e*.88,.16,1);this.exterior.visible=true;this.exterior.position.z=-e*1.45;this.exterior.position.x=-e*.25;this.exteriorMeshes.forEach(o=>{for(const m of(Array.isArray(o.material)?o.material:[o.material])){if(!m)return;const b=m.userData.baseOpacity??1;m.transparent=opacity<.999||b<1;m.opacity=b*opacity;m.depthWrite=opacity>.28}})}}
resize(){const w=this.host.clientWidth||innerWidth,h=this.host.clientHeight||innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
animate(t){this.explode+=(this.targetExplode-this.explode)*.075;this.parts.forEach(g=>g.position.copy(g.userData.base).addScaledVector(g.userData.dir,this.explode));if(this.autoRotate){const rot=Math.sin(t*.00016)*.07-.18;this.interior.rotation.y=rot;if(this.exterior)this.exterior.rotation.y=Math.PI+rot}else if(this.exterior)this.exterior.rotation.y=Math.PI+this.interior.rotation.y;this.updateVisibility();if(this.beam){const u=(t*.00028)%1;this.beamDot.position.copy(this.beamCurve.getPointAt(u));const scanX=Math.sin(t*.004)*2.0,scanY=Math.sin(t*.0017)*1.3;this.beamCurve.points[3].set(scanX*.18,scanY*.18,.22);this.beamLine.geometry.dispose();this.beamLine.geometry=new THREE.TubeGeometry(this.beamCurve,50,.014,8,false)}this.controls.update();this.renderer.render(this.scene,this.camera);requestAnimationFrame(this.animate)}
}
